export default class Commands {
    static mountain = "mountain"
    static pipe = "pipe"
    static pipeseam = "pipeseam"
    static plains = "plains"
    static reef = "reef"
    static river = "river"
    static roads = "roads"
    static sea = "sea"
    static shoal = "shoal"
    static woods = "woods"
    static base = "base"
    static hq = "hq"
    static infantry = "infantry"
    static megatank = "megatank"
    static recon = "recon"
    static clear = "clear"
    static selectedplayer = "selectedplayer"
}
